server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

database:
  driverClass: com.mysql.jdbc.Driver
  url: 'jdbc:mysql://localhost:3306/niping_db?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8_general_ci'
  user: root
  password: 'root'
  properties:
      charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionWhileIdle: true
  checkConnectionOnBorrow: true

# Logging settings.
logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./logs/application.log
      archivedLogFilenamePattern: logs/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: "Asia/Shanghai"
      maxFileSize: 20MB

views:
  .mustache:
    cache: false

sap:
  monitor:
    #unit: second
    lostTime: 30
job:
  roundTripTimeB: 1
  roundTripTimeL: 10
  bandwidthB: 100000
  bandwidthL: 10
  stabilityB: 200
  stabilityL: 36000
  stabilityD: 1000
  idleTimeoutD: 36000